import assert from "node:assert/strict"
import { test } from "node:test"

import {
  IGNORE_ENTRIES,
  buildCursorignore,
  defaultIgnoreState,
  enabledIgnoreCount,
  mergeIgnoreState,
  parseCursorignore,
  sanitizeCustomPatterns,
} from "./cursorignore"

test("defaults enable the recommended patterns only", () => {
  const state = defaultIgnoreState()
  assert.equal(state["node_modules/"], true)
  assert.equal(state["*.log"], false)
  assert.equal(enabledIgnoreCount(state), IGNORE_ENTRIES.filter((entry) => entry.recommended).length)
})

test("buildCursorignore groups enabled patterns under comment headers", () => {
  const state = defaultIgnoreState()
  const body = buildCursorignore(state)
  assert.match(body, /^# Generated by Cursor Manager/)
  assert.match(body, /# Dependencies\nnode_modules\//)
  assert.match(body, /# Secrets\n[\s\S]*\.env/)
  assert.ok(body.endsWith("\n"))
  assert.doesNotMatch(body, /\*\.log/)
})

test("buildCursorignore omits groups with no enabled patterns", () => {
  const state = defaultIgnoreState()
  for (const entry of IGNORE_ENTRIES) {
    if (entry.group === "Secrets") {
      state[entry.pattern] = false
    }
  }
  const body = buildCursorignore(state)
  assert.doesNotMatch(body, /# Secrets/)
  assert.match(body, /# Dependencies/)
})

test("buildCursorignore with nothing selected yields just the header", () => {
  const state: Record<string, boolean> = {}
  for (const entry of IGNORE_ENTRIES) {
    state[entry.pattern] = false
  }
  assert.equal(buildCursorignore(state), "# Generated by Cursor Manager\n")
})

test("mergeIgnoreState keeps known booleans and ignores junk", () => {
  const merged = mergeIgnoreState({ "node_modules/": false, "not.a.pattern": true })
  assert.equal(merged["node_modules/"], false)
  assert.equal("not.a.pattern" in merged, false)
  assert.equal(merged["dist/"], true)
})

test("sanitizeCustomPatterns trims, dedupes, and drops catalog/comment/blank entries", () => {
  const result = sanitizeCustomPatterns([" tmp/ ", "tmp/", "node_modules/", "# comment", "", 42, "*.bak"])
  assert.deepEqual(result, ["tmp/", "*.bak"])
})

test("buildCursorignore appends a Custom group and counts custom patterns", () => {
  const state = defaultIgnoreState()
  const body = buildCursorignore(state, ["tmp/", "*.bak"])
  assert.match(body, /# Custom\ntmp\/\n\*\.bak/)
  assert.equal(enabledIgnoreCount(state, ["tmp/"]), enabledIgnoreCount(state) + 1)
})

test("parseCursorignore toggles known patterns and keeps unknowns as custom", () => {
  const { enabled, custom } = parseCursorignore(
    "# Deps\nnode_modules/\ndist/\nsrc/generated/\n\n*.tmp",
  )
  assert.equal(enabled["node_modules/"], true)
  assert.equal(enabled["dist/"], true)
  assert.equal(enabled[".env"], false)
  assert.deepEqual(custom, ["src/generated/", "*.tmp"])
})
