export type IgnoreEntry = {
  pattern: string
  group: string
  description: string
  recommended: boolean
}

/**
 * Recommended `.cursorignore` entries. Per the /steroids playbook: exclude
 * dependencies, build output, coverage, large media, and secrets — but never
 * block source the user needs, so entries are individually toggleable.
 */
export const IGNORE_ENTRIES: IgnoreEntry[] = [
  { pattern: "node_modules/", group: "Dependencies", description: "Installed packages", recommended: true },
  { pattern: ".pnp/", group: "Dependencies", description: "Yarn Plug'n'Play", recommended: true },
  { pattern: ".venv/", group: "Dependencies", description: "Python virtualenv", recommended: true },
  { pattern: "dist/", group: "Build output", description: "Bundled output", recommended: true },
  { pattern: "build/", group: "Build output", description: "Build artifacts", recommended: true },
  { pattern: ".next/", group: "Build output", description: "Next.js cache/output", recommended: true },
  { pattern: "out/", group: "Build output", description: "Static export", recommended: true },
  { pattern: "coverage/", group: "Build output", description: "Test coverage reports", recommended: true },
  { pattern: "*.log", group: "Build output", description: "Log files", recommended: false },
  { pattern: "*.mp4", group: "Large media", description: "Video files", recommended: true },
  { pattern: "*.mov", group: "Large media", description: "Video files", recommended: true },
  { pattern: "*.zip", group: "Large media", description: "Archives", recommended: true },
  { pattern: "*.pdf", group: "Large media", description: "PDFs", recommended: false },
  { pattern: ".env", group: "Secrets", description: "Local environment file", recommended: true },
  { pattern: ".env.*", group: "Secrets", description: "Per-mode environment files", recommended: true },
  { pattern: "*.pem", group: "Secrets", description: "Private keys / certs", recommended: true },
  { pattern: "*.key", group: "Secrets", description: "Key material", recommended: true },
]

export const IGNORE_GROUPS: string[] = [...new Set(IGNORE_ENTRIES.map((entry) => entry.group))]

export type IgnoreState = Record<string, boolean>

export function defaultIgnoreState(): IgnoreState {
  const state: IgnoreState = {}
  for (const entry of IGNORE_ENTRIES) {
    state[entry.pattern] = entry.recommended
  }
  return state
}

export function mergeIgnoreState(value: unknown): IgnoreState {
  const base = defaultIgnoreState()
  if (!value || typeof value !== "object") {
    return base
  }
  const incoming = value as Record<string, unknown>
  for (const entry of IGNORE_ENTRIES) {
    if (typeof incoming[entry.pattern] === "boolean") {
      base[entry.pattern] = incoming[entry.pattern] as boolean
    }
  }
  return base
}

export function sanitizeCustomPatterns(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return []
  }
  const known = new Set(IGNORE_ENTRIES.map((entry) => entry.pattern))
  const out: string[] = []
  for (const item of value) {
    if (typeof item !== "string") {
      continue
    }
    const trimmed = item.trim()
    if (trimmed && !trimmed.startsWith("#") && !known.has(trimmed) && !out.includes(trimmed)) {
      out.push(trimmed)
    }
  }
  return out
}

/** Build a grouped `.cursorignore` file body from the enabled + custom patterns. */
export function buildCursorignore(state: IgnoreState, custom: string[] = []): string {
  const lines: string[] = ["# Generated by Cursor Manager"]
  for (const group of IGNORE_GROUPS) {
    const patterns = IGNORE_ENTRIES.filter(
      (entry) => entry.group === group && state[entry.pattern],
    ).map((entry) => entry.pattern)
    if (patterns.length === 0) {
      continue
    }
    lines.push("", `# ${group}`, ...patterns)
  }
  const customPatterns = sanitizeCustomPatterns(custom)
  if (customPatterns.length > 0) {
    lines.push("", "# Custom", ...customPatterns)
  }
  return `${lines.join("\n")}\n`
}

export function enabledIgnoreCount(state: IgnoreState, custom: string[] = []): number {
  return (
    IGNORE_ENTRIES.filter((entry) => state[entry.pattern]).length +
    sanitizeCustomPatterns(custom).length
  )
}

/** Parse an existing `.cursorignore` into catalog toggles plus unknown custom patterns. */
export function parseCursorignore(text: string): { enabled: IgnoreState; custom: string[] } {
  const seen = new Set(
    text
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line.length > 0 && !line.startsWith("#")),
  )
  const enabled: IgnoreState = {}
  for (const entry of IGNORE_ENTRIES) {
    enabled[entry.pattern] = seen.has(entry.pattern)
  }
  const custom = sanitizeCustomPatterns([...seen])
  return { enabled, custom }
}
